note

	description: "This file has been generated by WrapC. Do not edit. Changes will be lost!"

	generator: "Eiffel Wrapper Generator"
-- functions wrapper
class SDL_TIMER_FUNCTIONS_API


feature -- Access

	sdl_get_ticks: NATURAL
		external
			"C inline use <SDL.h>"
		alias
			"[
				return SDL_GetTicks ();
			]"
		end

	sdl_delay (ms: NATURAL)
		external
			"C inline use <SDL.h>"
		alias
			"[
				SDL_Delay ((Uint32)$ms);
			]"
		end

feature -- Externals

feature -- Externals Address

end
